type
	TKeys = (
		key_Left = 6,
		key_Right = 7,
		key_RETURN = 12,
		key_Up = 14,
		key_Down = 15,
		key_E = 19,
		key_ESC = 28,
		key_SPACE = 33,
		key_TAB = 44,
		key_BackSpc = 52,
		key_SHIFT_TAB = 108,
		key_CTRL_Left = 134,
		key_CTRL_Right = 135,
		key_CTRL_Up = 142,
		key_CTRL_Down = 143,
		key_CTRL_BackSpc = 180,
		key_DELETE = 180,
		key_INSERT = 183,

		key_SHIFT_Up = 206,
		key_SHIFT_Down = 207
);

	TTag = array[0..4] of byte;
