_sfxPtr        = 0;     // pointer to SFX data definition
_sfxPtrLo      = 0;     //
_sfxPtrHi      = 1;     //
_sfxNoteTabOfs = 2;     //


_chnOfs        = 3;     // SFX offset
_chnNote       = 4;     // SFX Note
_chnFreq       = 5;     // SFX Frequency

_chnMode       = 6;     // SFX Modulator mode

_chnModVal     = 7;     // SFX current Modulator value
_chnCtrl       = 8;     // SFX current distortion & volume

_tabPtr        = 12;    // pointer to TAB data definition
_tabPtrLo      = 12;    //
_tabPtrHi      = 13;    //
_tabOfs        = 14;    // TAB row offset
_tabRep        = 15;    // TAB current repeat value
