_sfxPtr        = 0;     // pointer to SFX data definition
_sfxPtrLo      = 0;     //
_sfxPtrHi      = 1;     //
_sfxNoteTabOfs = 2;     //


_chnOfs        = 4;     // SFX offset
_chnNote       = 5;     // SFX Note
_chnFreq       = 6;     // SFX Frequency

_chnMode       = 7;     // SFX Modulator mode

_chnModVal     = 8;     // SFX current Modulator value
_chnCtrl       = 9;     // SFX current distortion & volume

_tabPtr        = 10;    // pointer to TAB data definition
_tabPtrLo      = 10;    //
_tabPtrHi      = 11;    //
_tabOfs        = 12;    // TAB row offset
_tabRep        = 13;    // TAB current repeat value
